In [1]:
import pandas as pd
import numpy as np

In [2]:
disease= pd.read_csv("Datafile_070.csv")

In [3]:
disease.head()

,x,y,cell_id,population,infected_DM_0,infected_DM_1,infected_DM_2,infected_DM_3,u,var,sd,IoD,CoV
0,-2.265540,53.420453,6.504529e+18,22,0,1,2,2,1.25,0.916667,0.957427,0.733333,0.765942
1,-2.265596,53.429442,8.685601e+18,38,2,2,2,0,1.50,1.000000,1.000000,0.666667,0.666667
2,-2.265664,53.440228,-6.954263e+18,58,1,1,1,1,1.00,0.000000,0.000000,0.000000,0.000000
3,-2.265692,53.444722,-7.903445e+18,59,3,1,2,1,1.75,0.916667,0.957427,0.523810,0.547101
4,-2.265782,53.459104,8.320480e+18,166,2,4,0,3,2.25,2.916667,1.707825,1.296296,0.759033

In [4]:
disease.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3214 entries, 0 to 3213
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   x              3214 non-null   float64
 1   y              3214 non-null   float64
 2   cell_id        3214 non-null   float64
 3   population     3214 non-null   int64
 4   infected_DM_0  3214 non-null   int64
 5   infected_DM_1  3214 non-null   int64
 6   infected_DM_2  3214 non-null   int64
 7   infected_DM_3  3214 non-null   int64
 8   u              3214 non-null   float64
 9   var            3214 non-null   float64
 10  sd             3214 non-null   float64
 11  IoD            3214 non-null   float64
 12  CoV            3214 non-null   float64
dtypes: float64(8), int64(5)
memory usage: 326.6 KB

In [5]:
disease.isnull().sum()

x                0
y                0
cell_id          0
population       0
infected_DM_0    0
infected_DM_1    0
infected_DM_2    0
infected_DM_3    0
u                0
var              0
sd               0
IoD              0
CoV              0
dtype: int64

In [6]:
disease["risk_score"] = disease["u"] * (1 + disease["CoV"])

In [7]:
disease.describe()

,x,y,cell_id,population,infected_DM_0,infected_DM_1,infected_DM_2,infected_DM_3,u,var,sd,IoD,CoV,risk_score
count,3214.000000,3214.000000,3.214000e+03,3214.000000,3214.000000,3214.000000,3214.000000,3214.000000,3214.000000,3214.000000,3214.000000,3214.000000,3214.000000,3214.000000
mean,-2.234937,53.501756,1.857974e+17,94.127878,1.056627,1.029247,0.999689,1.043559,1.032281,0.935102,0.807322,0.978685,1.375128,1.839602
std,0.029238,0.048390,5.382116e+18,75.361923,2.273249,2.251206,2.174106,2.219366,2.066611,1.894920,0.532374,0.510764,0.618735,2.443187
min,-2.289842,53.406950,-9.216431e+18,2.000000,0.000000,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,0.750000
25%,-2.259585,53.460010,-4.409344e+18,52.000000,0.000000,0.000000,0.000000,0.000000,0.250000,0.250000,0.500000,0.666667,0.816497,0.750000
50%,-2.237586,53.504129,2.713952e+17,77.500000,1.000000,0.000000,1.000000,1.000000,0.500000,0.333333,0.577350,1.000000,1.276569,1.077350
75%,-2.213546,53.534674,4.819315e+18,112.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.916667,0.957427,1.000000,2.000000,2.077350
max,-2.130574,53.643526,9.222997e+18,811.000000,37.000000,42.000000,40.000000,39.000000,37.000000,38.250000,6.184658,4.714286,2.000000,41.432883

In [8]:
bins = [0, 1.0, 2.0, disease["risk_score"].max()]
labels = ["Low", "Medium", "High"]
disease["risk_category"] = pd.cut(disease["risk_score"], bins=bins, labels=labels, include_lowest=True)

In [9]:
print(disease["risk_category"].value_counts())

risk_category
Low       1287
Medium    1118
High       809
Name: count, dtype: int64

In [13]:
bins = [0, 0.3, 1, 5, disease["u"].max()]
labels = ["Negligible", "Low", "Medium", "High"]
disease["u_category"] = pd.cut(disease["u"], bins=bins, labels=labels, include_lowest=True)

In [11]:
print(disease["u_category"].value_counts())

u_category
Negligible    1262
Low           1202
Medium         690
High            60
Name: count, dtype: int64

In [12]:
disease.to_csv("D:/PowerBI_disease_data.csv", index=False)